SELECT CITY_IDX, COUNTRY_IDX, CITY_CODE, CITY_IMAGE_URL ,CITY_CURRENCY, CITY_DEFAULT_COST, CITY_AIR_DEFAULT_COST, CITY_IN_SERVICE, 
        	(SELECT CITY_NM FROM TB_CITY_LOCAL TCL WHERE TCL.CITY_CODE=TC.CITY_CODE AND TCL.LANGUAGE_CODE="ko") AS CITY_NM, 
        	(SELECT CITY_DESC FROM TB_CITY_LOCAL TCL WHERE TCL.CITY_CODE=TC.CITY_CODE AND TCL.LANGUAGE_CODE="ko") AS CITY_DESC
        FROM TB_CITY TC
        WHERE CITY_IN_SERVICE = 1 || CITY_IN_SERVICE = 2
        ORDER BY CITY_SORT ASC



SELECT CITY_IDX, COUNTRY_IDX, CITY_CODE, CITY_IMAGE_URL ,CITY_CURRENCY, CITY_DEFAULT_COST, CITY_AIR_DEFAULT_COST, CITY_IN_SERVICE,
        SUBSTRING_INDEX(CITY_NM_CITY_DESC, '_seperator_', 1) AS CITY_NM,
        SUBSTRING_INDEX(CITY_NM_CITY_DESC, '_seperator_', 2) AS CITY_DESC 
        FROM
(SELECT CITY_IDX, COUNTRY_IDX, CITY_CODE, CITY_IMAGE_URL ,CITY_CURRENCY, CITY_DEFAULT_COST, CITY_AIR_DEFAULT_COST, CITY_IN_SERVICE,
        (SELECT concat(CITY_NM, '_seperator_', CITY_DESC) FROM TB_CITY_LOCAL TCL WHERE TCL.CITY_CODE=TC.CITY_CODE AND TCL.LANGUAGE_CODE="ko") AS CITY_NM_CITY_DESC
        FROM TB_CITY TC
        WHERE CITY_IN_SERVICE = 1 || CITY_IN_SERVICE = 2
        ORDER BY CITY_SORT ASC)


SELECT CITY_IDX, COUNTRY_IDX, CITY_CODE, CITY_IMAGE_URL ,CITY_CURRENCY, CITY_DEFAULT_COST, CITY_AIR_DEFAULT_COST, CITY_IN_SERVICE, CITY_NM, CITY_DESC
FROM
(SELECT CITY_IDX, COUNTRY_IDX, CITY_CODE, CITY_IMAGE_URL ,CITY_CURRENCY, CITY_DEFAULT_COST, CITY_AIR_DEFAULT_COST, CITY_IN_SERVICE
FROM TB_CITY TC
WHERE CITY_IN_SERVICE = 1 || CITY_IN_SERVICE = 2
ORDER BY CITY_SORT ASC) A
LEFT JOIN
(SELECT CITY_NM, CITY_DESC FROM TB_CITY_LOCAL TCL WHERE TCL.CITY_CODE=TC.CITY_CODE AND TCL.LANGUAGE_CODE="ko") B
ON
A.CITY_IDX = B.CITY_IDX AND
A.COUNTRY_IDX = B.COUNTRY_IDX


        	(SELECT CITY_NM FROM TB_CITY_LOCAL TCL WHERE TCL.CITY_CODE=TC.CITY_CODE AND TCL.LANGUAGE_CODE="ko") AS CITY_NM, 
        	(SELECT CITY_DESC FROM TB_CITY_LOCAL TCL WHERE TCL.CITY_CODE=TC.CITY_CODE AND TCL.LANGUAGE_CODE="ko") AS CITY_DESC
        